#!/usr/bin/env python3
"""Generate a Kora 2.0 Kafka publisher (@KafkaPublisher) for Java or Kotlin.

Produces a publisher interface with one @Topic method group per topic, the matching
kafka.producer.<name> HOCON snippet and, optionally, an integration test. Useful next to a
consumer for dead-letter queues and read-process-write pipelines.

Kora 2.0 facts this generator encodes:
  * @KafkaPublisher and @KafkaPublisher.Topic live in io.koraframework.kafka.common.annotation
  * @KafkaPublisher("<path>") names the producer config section; @Topic("<path>") names a section
    holding `topic` (and optionally `partition`)
  * supported return types: void/Unit, RecordMetadata, Future<RecordMetadata>
  * a failed publish surfaces as io.koraframework.kafka.common.exceptions.KafkaPublishException
  * HOCON has no ${VAR:default}; use a literal followed by ${?VAR}
  * Testcontainers 2.x module is org.testcontainers:testcontainers-kafka

Examples:
  generate_producer.py --name Order --topics orders --package com.example
  generate_producer.py --name Order --topics orders,orders-dlq --lang kotlin --with-tests
  generate_producer.py --name Order --topics orders --dry-run
"""

import argparse
import re
import sys
from pathlib import Path


def render(template: str, **values: str) -> str:
    out = template
    for key, value in values.items():
        out = out.replace("{{" + key + "}}", value)
    return out


def method_suffix(topic: str) -> str:
    """orders-dlq -> OrdersDlq, so several topics do not collide on one method name."""
    parts = re.split(r"[^0-9A-Za-z]+", topic)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def config_key(topic: str) -> str:
    """orders-dlq -> ordersDlq, a HOCON-safe section name."""
    suffix = method_suffix(topic)
    return suffix[:1].lower() + suffix[1:]


JAVA_PUBLISHER = """package {{PACKAGE}}.publisher;

import io.koraframework.kafka.common.annotation.KafkaPublisher;
import io.koraframework.kafka.common.annotation.KafkaPublisher.Topic;
import org.apache.kafka.clients.producer.RecordMetadata;
import org.apache.kafka.common.header.Headers;

import java.util.concurrent.Future;

/**
 * Kafka publisher for topics: {{TOPICS_DOC}}
 * Config path: kafka.producer.{{NAME}}
 *
 * Generated by the kora-kafka-consumer skill. A publish failure is reported as
 * KafkaPublishException with the broker error in getCause().
 */
@KafkaPublisher("kafka.producer.{{NAME}}")
public interface {{CLASS}} {
{{METHODS}}}
"""

JAVA_METHODS = """
    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    void send{{SUFFIX}}(String value);

    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    void send{{SUFFIX}}(String key, String value);

    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    void send{{SUFFIX}}(String key, String value, Headers headers);

    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    RecordMetadata send{{SUFFIX}}WithMeta(String value);

    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    Future<RecordMetadata> send{{SUFFIX}}Async(String value);
"""

KOTLIN_PUBLISHER = """package {{PACKAGE}}.publisher

import io.koraframework.kafka.common.annotation.KafkaPublisher
import io.koraframework.kafka.common.annotation.KafkaPublisher.Topic
import org.apache.kafka.clients.producer.RecordMetadata
import org.apache.kafka.common.header.Headers
import java.util.concurrent.Future

/**
 * Kafka publisher for topics: {{TOPICS_DOC}}
 * Config path: kafka.producer.{{NAME}}
 *
 * Generated by the kora-kafka-consumer skill. A publish failure is reported as
 * KafkaPublishException with the broker error in cause.
 */
@KafkaPublisher("kafka.producer.{{NAME}}")
interface {{CLASS}} {
{{METHODS}}}
"""

KOTLIN_METHODS = """
    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    fun send{{SUFFIX}}(value: String)

    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    fun send{{SUFFIX}}(key: String, value: String)

    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    fun send{{SUFFIX}}(key: String, value: String, headers: Headers)

    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    fun send{{SUFFIX}}WithMeta(value: String): RecordMetadata

    @Topic("kafka.producer.{{NAME}}.{{KEY}}")
    fun send{{SUFFIX}}Async(value: String): Future<RecordMetadata>
"""

CONFIG = """# Kora 2.0 Kafka publisher configuration for {{CLASS}}
# Generated by the kora-kafka-consumer skill.
#
# HOCON has no ${VAR:default}. Write the literal first, then override it with ${?VAR}.

kafka {
  producer {
    {{NAME}} {
      driverProperties {
        "bootstrap.servers" = "localhost:9092"
        "bootstrap.servers" = ${?KAFKA_BOOTSTRAP}
        "acks" = "all"
        "retries" = 3
        "linger.ms" = 5
      }

{{TOPIC_SECTIONS}}
      telemetry {
        # Both default to false in Kora 2.0
        logging.enabled = true
        metrics {
          enabled = true
          slo = [1, 10, 50, 100, 200, 500, 1000, 2000, 5000, 10000]
        }
        tracing.enabled = true
      }
    }
  }
}
"""

TOPIC_SECTION = """      {{KEY}} {
        topic = "{{TOPIC}}"
        # partition = 0
      }
"""

JAVA_TEST = """package {{PACKAGE}}.publisher;

import io.goodforgod.testcontainers.extensions.ContainerMode;
import io.goodforgod.testcontainers.extensions.kafka.ConnectionKafka;
import io.goodforgod.testcontainers.extensions.kafka.KafkaConnection;
import io.goodforgod.testcontainers.extensions.kafka.TestcontainersKafka;
import io.goodforgod.testcontainers.extensions.kafka.Topics;
import io.koraframework.test.extension.junit5.KoraAppTest;
import io.koraframework.test.extension.junit5.KoraAppTestConfigModifier;
import io.koraframework.test.extension.junit5.KoraConfigModification;
import io.koraframework.test.extension.junit5.TestComponent;
import {{PACKAGE}}.Application;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Integration test for {{CLASS}}. Subscribe BEFORE sending, otherwise the assertion races
 * the produce. The Testcontainers Kafka module is org.testcontainers:testcontainers-kafka in
 * Testcontainers 2.x, not org.testcontainers:kafka.
 */
@TestcontainersKafka(mode = ContainerMode.PER_RUN, topics = @Topics({"{{TOPIC}}"}))
@KoraAppTest(Application.class)
class {{CLASS}}Tests implements KoraAppTestConfigModifier {

    @ConnectionKafka
    private KafkaConnection connection;

    @TestComponent
    private {{CLASS}} publisher;

    @Override
    public KoraConfigModification config() {
        return KoraConfigModification.ofSystemProperty(
            "KAFKA_BOOTSTRAP", connection.params().bootstrapServers());
    }

    @Test
    void publishesValue() {
        var received = connection.subscribe("{{TOPIC}}");

        publisher.send{{SUFFIX}}("payload");

        assertTrue(received.assertReceivedAtLeast(1).stream()
            .anyMatch(event -> "payload".equals(event.value().asString())));
    }
}
"""

KOTLIN_TEST = """package {{PACKAGE}}.publisher

import io.goodforgod.testcontainers.extensions.ContainerMode
import io.goodforgod.testcontainers.extensions.kafka.ConnectionKafka
import io.goodforgod.testcontainers.extensions.kafka.KafkaConnection
import io.goodforgod.testcontainers.extensions.kafka.TestcontainersKafka
import io.goodforgod.testcontainers.extensions.kafka.Topics
import io.koraframework.test.extension.junit5.KoraAppTest
import io.koraframework.test.extension.junit5.KoraAppTestConfigModifier
import io.koraframework.test.extension.junit5.KoraConfigModification
import io.koraframework.test.extension.junit5.TestComponent
import {{PACKAGE}}.Application
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

/**
 * Integration test for {{CLASS}}. Subscribe BEFORE sending, otherwise the assertion races
 * the produce.
 */
@TestcontainersKafka(mode = ContainerMode.PER_RUN, topics = Topics("{{TOPIC}}"))
@KoraAppTest(Application::class)
class {{CLASS}}Tests : KoraAppTestConfigModifier {

    @ConnectionKafka
    lateinit var connection: KafkaConnection

    @TestComponent
    lateinit var publisher: {{CLASS}}

    override fun config(): KoraConfigModification =
        KoraConfigModification.ofSystemProperty("KAFKA_BOOTSTRAP", connection.params().bootstrapServers())

    @Test
    fun publishesValue() {
        val received = connection.subscribe("{{TOPIC}}")

        publisher.send{{SUFFIX}}("payload")

        assertTrue(received.assertReceivedAtLeast(1).any { it.value().asString() == "payload" })
    }
}
"""


def emit(path: Path, content: str, dry_run: bool, skip_if_exists: bool = False) -> None:
    if dry_run:
        print("[dry-run] would write %s (%d bytes)" % (path, len(content.encode("utf-8"))))
        return
    if skip_if_exists and path.exists():
        print("exists, not overwritten: %s" % path)
        print("--- append the following manually ---")
        print(content)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print("wrote %s" % path)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a Kora 2.0 Kafka publisher (@KafkaPublisher)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument("--name", "-n", required=True,
                        help='Publisher name; "Publisher" is appended when missing')
    parser.add_argument("--topics", "-t", required=True, nargs="+",
                        help="Kafka topics (space or comma separated)")
    parser.add_argument("--package", "-p", default="com.example",
                        help="Base package (default: com.example)")
    parser.add_argument("--lang", "-l", choices=["java", "kotlin"], default="java",
                        help="Target language (default: java)")
    parser.add_argument("--output", "-o", default="src/main",
                        help="Main source-set directory (default: src/main)")
    parser.add_argument("--with-tests", action="store_true",
                        help="Also generate an integration test")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be written without touching the filesystem")

    args = parser.parse_args()

    topics: list[str] = []
    for raw in args.topics:
        topics.extend(t.strip() for t in raw.split(",") if t.strip())
    if not topics:
        parser.error("--topics must name at least one topic")

    cls = args.name if args.name.endswith("Publisher") else args.name + "Publisher"
    name = cls[0].lower() + cls[1:]

    lang_dir = "kotlin" if args.lang == "kotlin" else "java"
    ext = "kt" if args.lang == "kotlin" else "java"
    package_dir = args.package.replace(".", "/")

    main_root = Path(args.output)
    publisher_path = main_root / lang_dir / package_dir / "publisher" / ("%s.%s" % (cls, ext))
    config_file = main_root / "resources" / ("%s.conf" % name)
    test_path = (main_root.parent / "test" / lang_dir / package_dir / "publisher"
                 / ("%sTests.%s" % (cls, ext)))

    # One method group per topic, suffixed so several topics never collide on one signature.
    single = len(topics) == 1
    methods_tpl = KOTLIN_METHODS if args.lang == "kotlin" else JAVA_METHODS
    methods = "".join(
        render(methods_tpl, NAME=name, KEY=config_key(t),
               SUFFIX="" if single else method_suffix(t))
        for t in topics
    )

    emit(publisher_path,
         render(KOTLIN_PUBLISHER if args.lang == "kotlin" else JAVA_PUBLISHER,
                PACKAGE=args.package, CLASS=cls, NAME=name,
                TOPICS_DOC=", ".join(topics), METHODS=methods),
         args.dry_run)

    topic_sections = "".join(
        render(TOPIC_SECTION, KEY=config_key(t), TOPIC=t) + "\n" for t in topics
    )
    emit(config_file,
         render(CONFIG, CLASS=cls, NAME=name, TOPIC_SECTIONS=topic_sections),
         args.dry_run, skip_if_exists=True)

    if args.with_tests:
        emit(test_path,
             render(KOTLIN_TEST if args.lang == "kotlin" else JAVA_TEST,
                    PACKAGE=args.package, CLASS=cls, TOPIC=topics[0],
                    SUFFIX="" if single else method_suffix(topics[0])),
             args.dry_run)

    print("")
    print("interface   : %s.publisher.%s" % (args.package, cls))
    print("config path : kafka.producer.%s" % name)
    print("topics      : %s" % ", ".join(topics))
    print("")
    print("Next: merge %s into application.conf, add KafkaModule to the @KoraApp interface,"
          % config_file)
    print("      then ./gradlew build")


if __name__ == "__main__":
    main()
